### ISSUE TITLE
Duniverse is broken on non-English systems

### ISSUE THREAD

**Issue by TheLortex** [ocamllabs/opam-monorepo#114]
When using `git_default_branch`, duniverse makes a call to `git remote show` which has an internationalized output.
`HEAD branch : ...` is translated to `Branche HEAD : ...` in French, thus breaking the following part of the code:

https://github.com/ocamllabs/duniverse/blob/07f687043867416cfe9dc7afe493ac85e44d3d69/lib/exec.ml#L130-L133

**Comment by emillon** [comment]
It's possible to pass LC_ALL=C, but it seems better to use a plumbing command for this. I think `git ls-remote --symref origin HEAD`is the one?
