### ISSUE TITLE
Fails for when OPAMROOT is set to something other than the default directory

### ISSUE THREAD

**Issue by leojrfs** [ocamllabs/opam-monorepo#197]
When `OPAMROOT` is set to something other than the default directory, `opam-monorepo` fails:

```
[ERROR] Opam has not been initialised, please run `opam init'
opam-monorepo: internal error, uncaught exception:
               OpamStd.OpamSys.Exit(50)
               Raised at file "src/core/opamStd.ml", line 1042, characters 15-29
               Called from file "src/state/opamGlobalState.ml", line 60, characters 4-113
               Called from file "src/state/opamGlobalState.ml", line 185, characters 11-20
               Called from file "cmdliner_term.ml", line 25, characters 19-24
               Called from file "cmdliner.ml", line 33, characters 27-34
               Called from file "cmdliner.ml", line 117, characters 32-39
make: *** [Makefile:61: deps-pull] Error 125
```

It doesn't seem like monorepo is initialising the opam state in the same way opam does, so the `OPAMROOT` variable is never read.

**Comment by NathanReb** [comment]
Thanks for reporting this, good catch!

I'll investigate, it must be just an omission on our part, I basically copied the opam initialization code from  another plugin without giving it much more thought.

**Comment by Leonidas-from-XIV** [comment]
@leojrfs You can try the code in the linked PR, it should fix it. We're aiming to get this fixed soon.
