### ISSUE TITLE
Optional (depopts) dependencies are forced

### ISSUE THREAD

**Issue by copy** [ocamllabs/opam-monorepo#205]
For example, the following opam file:

```
opam-version: "2.0"
depends: [
  "logs"
]
```

Produces:

```
opam-version: "2.0"
synopsis: "opam-monorepo generated lockfile"
maintainer: "opam-monorepo"
depends: [
  "base-bigarray" {= "base"}
  "base-bytes" {= "base"}
  "base-threads" {= "base"}
  "base-unix" {= "base"}
  "cmdliner" {= "1.0.4+dune"}
  "cppo" {= "1.6.8"}
  "csexp" {= "1.5.1"}
  "dune" {= "2.9.1"}
  "dune-configurator" {= "2.9.1"}
  "findlib" {= "1.8.1+dune"}
  "fmt" {= "0.8.9+dune"}
  "logs" {= "0.7.0+dune"}
  "lwt" {= "5.4.2"}
  "mmap" {= "1.1.0"}
  "ocaml" {= "4.13.1"}
  "ocaml-base-compiler" {= "4.13.1"}
  "ocaml-config" {= "2"}
  "ocaml-options-vanilla" {= "1"}
  "ocamlfind" {= "1.8.1+dune"}
  "ocplib-endian" {= "1.1"}
  "result" {= "1.5"}
  "seq" {= "base+dune"}
  "stdlib-shims" {= "0.3.0"}
]
```

Most of which are [optional](https://github.com/dbuenzli/logs/blob/master/opam#L10-L22).

**Comment by copy** [comment]
> opam-monorepo ignores depopts. This happens because the dune port of logs declares some of them as regular dependencies (see here).

Ah, I see. I hadn't considered that the logs-dune package might have a different opam file from the official one.

> If you have a need for a minimal logs installation in an opam monorepo setup please let me know so we can try to improve the port.

That would be nice :-)

**Comment by NathanReb** [comment]
I'm closing this as it is unrelated to opam-monorepo itself. I'll re-open an issue on [dune-universe/opam-overlays](https://github.com/dune-universe/opam-overlays) as this is where it should be fixed.

If I'm late to do so, please feel free to re-open it there yourself!
