### ISSUE TITLE
How to convince opam-monorepo that a package can use dune

### ISSUE THREAD

**Issue by emillon** [ocamllabs/opam-monorepo#208]
Since version 1.0.3, [cmdliner embeds a dune file](https://github.com/dbuenzli/cmdliner/blob/db4d02a9eb47b5c43127a67cb121004b03ea3719/CHANGES.md#v103-2018-11-26-zagreb) which can be used to build the library. But this fact is absent from the opam metadata. Can we somehow let opam-monorepo trust us? Would adding dune as depopt work?

**Comment by NathanReb** [comment]
I'm closing this as I think the depopts solution is a decent one!
