### ISSUE TITLE
Running opam-monorepo in a project without `dune-project` file at the root crashes

### ISSUE THREAD

**Issue by NathanReb** [ocamllabs/opam-monorepo#225]
It does it the following way:
```
$ opam monorepo lock
==> Using 2 locally scanned packages as the roots.
opam-monorepo: internal error, uncaught exception:
               (Sys_error
                 "/home/nathan/code/test-multi-opam-monorepo/dune-project: No such file or directory")
               Raised by primitive operation at Stdlib.open_in_gen in file "stdlib.ml", line 399, characters 28-54
               Called from Stdlib.open_in in file "stdlib.ml" (inlined), line 404, characters 2-45
               Called from Sexplib__Pre_sexp.gen_load_rev_sexps in file "duniverse/sexplib/src/pre_sexp.ml", line 688, characters 11-23
               Called from Sexplib__Pre_sexp.load_rev_sexps in file "duniverse/sexplib/src/pre_sexp.ml" (inlined), line 699, characters 31-75
               Called from Sexplib__Pre_sexp.load_sexps in file "duniverse/sexplib/src/pre_sexp.ml" (inlined), line 700, characters 36-62
               Called from Duniverse_lib__Dune_file.Raw.as_sexps in file "lib/dune_file.ml", line 73, characters 11-59
               Called from Duniverse_lib__Repo.project_name in file "lib/repo.ml", line 55, characters 2-37
               Called from Duniverse_lib__Repo.lockfile.(fun) in file "lib/repo.ml", line 74, characters 9-23
               Called from Duniverse_cli__Lock.run.(fun) in file "cli/lock.ml", line 233, characters 2-55
               Called from Cmdliner_term.app.(fun) in file "duniverse/cmdliner/src/cmdliner_term.ml", line 25, characters 19-24
               Called from Cmdliner.Term.term_result.(fun) in file "duniverse/cmdliner/src/cmdliner.ml", line 33, characters 27-34
               Called from Cmdliner.Term.run in file "duniverse/cmdliner/src/cmdliner.ml", line 117, characters 32-39
```

Exitting gracefully while still complaining about the project not having a root dune-project is the least (and best) we can do here!

**Comment by emillon** [comment]
I hit that one in the past. IIRC it only happens when there are several opam files, but I'm not sure.

**Comment by NathanReb** [comment]
It does, it will happen when trying to determine the lockfile name to use. To be even more accurate it will happen when running `opam monorepo lock` and those conditions are met:
1. `--lockfile` option is not used
2. there are more than one target package i.e.:
    + more than one target package was explicitly passed as arguments
    + `--recurse` was passed and there is more than one package defined in the whole workspace
    + `--recurse` was not passed and there is more than one package defined at the root of the project 
 
At this point opam-monorepo will want to use the project name as definied in the dune-project to use it as the lockfile name and fail ungracefully.

The fix I'm working on will do two things:
- properly report the missing dune-project
- tell the user why that happened and how to fix it (add a dune-project or explicitly pass the target lockfile using the CLI option)
