### ISSUE TITLE
Adding package to `pin-depends` excludes it from lockfile

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocamllabs/opam-monorepo#230]
As it was noted that `opam-monorepo` can't be built when it is pinned like `opam pin add opam-monorepo --dev` because it is missing the patched `opam-0install-solver` I decided to add it to the `opam-monorepo.opam` (via the template).

This unfortunately causes the solver to become blind to the package (probably since it assumes the package is installed via the pin), thus not including it in the generated lockfile.

Removing the `pin-depends` makes the package appear in the lockfile again, but of course not the right commit since opam-monorepo does not know that we need the `git` version of this package.

**Comment by NathanReb** [comment]
I think this must have been broken recently as it used to work. Can you try and bisect what caused this?

**Comment by NathanReb** [comment]
The latest release properly handles pin-depends! I'll bisect this to find out how we broke this!

**Comment by Leonidas-from-XIV** [comment]
Fixed by #233.
