### ISSUE TITLE
build output contains warnings that (maybe) should be skipped

### ISSUE THREAD

**Issue by raphael-proust** [ocamllabs/opam-monorepo#249]
When building a project with an opam-monorepo, I get deprecation warnings for some of the dependencies. These warnings are omitted when installing the dependencies via opam. Maybe the `duniverse/dune` file could include a stanza to suppress those warnings?

Steps to reproduce:

```
git clone git@gitlab.com:raphael-proust/laptop-status.git
cd laptop-status
opam monorepo pull
dune build
```

This produces `Alert deprecated: Toploop.directive_table` for multiple dependencies.

The warnings are repeated when the build is re-run, even if none of the dependencies have changed.

```
dune build
```

**Comment by NathanReb** [comment]
To clarify the generated `duniverse` folder is marked as vendored, in part for this purpose.

**Comment by NathanReb** [comment]
This has been fixed upstream in dune now and released see: https://github.com/ocaml/dune/pull/5683!

I'm closing this issue but please feel free to re-open if the issue persists with dune 3.2.0 or higher!
