### ISSUE TITLE
Add a mechanism to prefer mirage ports when available

### ISSUE THREAD

**Issue by NathanReb** [ocamllabs/opam-monorepo#251]
We recently created [dune-universe/mirage-opam-overlays](https://github.com/dune-universe/mirage-opam-overlays) for mirage specific ports (mostly ports allowing cross compilation).

The mirage tool will set both the regular dune overlays [dune-universe/opam-overlays](https://github.com/dune-universe/opam-overlays) and the mirage one.

The dune overlays compose well with upstream opam-repository since if a new release hits upstream there are two possible cases:
1. it builds with `dune` in which case we do not need a new `+dune` port for it in the dune overlays and the opam-monorepo solver will pick it, everyone is happy.
2. It does not build with dune, meaning until we add a new port for it, the solver will ignore it still picking the lastest available dune port.

This does not apply with `+mirage` ports as they are not strictly necessary for opam-monorepo, most users don't need to cross compile. This means that if a higher version is released, that does not cross compile, the solver will pick it instead (assuming it builds with dune and fits the constraints of course), therefore breaking mirage builds until an updated mirage port is released or the constraints are updated, this makes the whole thing very unstable.

Our plan to fix this is to add somewhere in the opam metadata of mirage ports the information that the package can be cross compiled. With this information available we can then have a mode of opam-monorepo where the solver will preferably select a "cross-compilable" version if it exists (by filtering out the other ones) or just keep the default behaviour if there is no such version of a package.

We should use a regular field that is otherwise ignored, something like `tags` maybe, so we can potentially add it to packages upstream so this behaviour can be enforced even once cross-compilation compat ports have been upstreamed.

**Comment by NathanReb** [comment]
CC @TheLortex @dinosaure, I'll be working on this shortly so we're ready for the next release of zarith!

**Comment by NathanReb** [comment]
Note this makes for a very good candidate for Test Driven Development once we merged #250 !

**Comment by TheLortex** [comment]
For this my suggestion would be to use the `available` field of opam declarations. (https://opam.ocaml.org/doc/Manual.html#opamfield-available)
In particular, we could choose an `os` entry called `mirage`, so that the non-cross-compilation-friendly zarith port would be marked unavailable on that platform. It would only be a matter of adding `available: [os != "mirage"]`.

I we want to be more precise, we'd have to create a new variable to account for the cross-compilation behaviors (host OS != target OS). For example, we could define two variables: `host-os` and `target-os`, and specify that `os = target-os` for compatibility purposes, and then package maintainers could introduce solver restrictions such as: 
`available: [ (host-os = "linux" & target-os = "mirage" & target-system = "solo5")]` for a mirage-specific package that builds only on linux.

So as a first I'd suggest to simply allow customizing the `os` field in the solver, and see what happens. What do you think?

**Comment by NathanReb** [comment]
The problem I can see with that solution is that it might require updating regular packages and I'd prefer a solution that will behave well without updating older packages in the upstream repository. I.e. whatever we choose, no package should have to opt out of the behaviour we will introduce, it should be an opt in thing.

I think the available field is a bit too risky here, it is used by opam itself and could cause all sorts of troubles if we mis-specify things

My impression is that the sort of patches we're talking about here will require you to build everything from the same workspace using opam-monorepo to cross compile so I don't think it makes sense trying to make it work with regular opam.

I may not have the full picture in mind and that might be why your suggestion seems a bit complex to me at the moment. Do you concrete examples where the usage of the `available` field comes in handy compared to a simpler, tag based solution?

To clarify, what I had in mind was to add a `mirage-x-compile` of some sort tag to `+mirage` ports or packages that have new releases that can be cross compiled in a duniverse. Now imagine we consider package `a` with the following versions:
| Version | Builds with dune | Cross compiles |
| --- | --- | --- |
| 0.1 | :negative_squared_cross_mark: | :negative_squared_cross_mark:  |
| 0.1+dune | :negative_squared_cross_mark: | :heavy_check_mark: |
| 0.1+dune+mirage | :heavy_check_mark: | :heavy_check_mark: |
| 0.2 | :heavy_check_mark: | :negative_squared_cross_mark: |
| 0.2.1 | :heavy_check_mark: | :heavy_check_mark: |

Before `0.2.1` is released, only the `+mirage` version would have the tag so if you don't have the mirage overlays, the opam-monorepo solver sees no package with the tag and considers versions `0.1+dune` and `0.2`. If you had the mirage overlays, it sees one version exists with the tag, it filters out all the other ones and only considers version `0.1+dune+mirage`.
Once `0.2.1` is released, we make it so it has the tag upstream in `opam-repository`. The solver will consider only 0.2.1 because it will always see a version marked with the tag from now on. It will eventually see `0.1+dune+mirage` if you have the ovrlays setup but will likely prefer the higher version of `0.2.1`.

Of course all of this would be opt in in `opam-monorepo` but mirage would always run it in that mode. It would be up to users whether they want to enable this for their own usage.

**Comment by TheLortex** [comment]
I agree that the flag is sufficient for our use case. I'm trying to think about the longer-term story where the cross-compilation could be a first class citizen in the opam world. It is not yet the case, but having the metadata ready for the transition looks useful. 

As a particular example, I'm thinking of mirage device drivers, for example `mirage-solo5`. `mirage-solo5` depend on the solo5 kernel API to implement its feature, and thus is _cross-compiled_ and available only when the target is _solo5_ (i.e. a subset of mirage targets). With only a flag, there's no way to enforce that and a bad dependency specification could try to fetch `mirage-solo5` for another target.

Another example would be a project that supports unix for all processors, and mirage but only on x86. The specification would be `available: [ os = "unix" | (os = "mirage" & arch = "x86") ]` but there's no way to enforce that with just a flag.

In any case, as I'm thinking about it, the full metadata story is much more complex than what I've presented here. We'd also need to annotate _host_ and _target_ dependencies (for example `cstruct` as target (os = mirage), `ppx_cstruct` as host (os = unix)).

--- 
So let's start with your solution, hacking with the _available_ field will be risky and require more in-depth thoughts.

**Comment by NathanReb** [comment]
Ok sounds good!

Once we have this working I'm of course happy to look into the longer term, `os` based solution with you!

**Comment by dinosaure** [comment]
Yes, we should give a try to the simpler solution first and improve it step by step. By this way, we ensure that we don't break anything for the ecosystem.
