### ISSUE TITLE
Duniverse init seems to pull test deps of pinned packages

### ISSUE THREAD

**Issue by NathanReb** [ocamllabs/opam-monorepo#89]
It appears that when pinning a package, `duniverse init` will add its test dependencies to the lockfile.

You can clone https://github.com/NathanReb/duniverse-transitive-test-deps-bug and follow the steps described in the README to reproduce this.

**Comment by rizo** [comment]
So, just to clarify: is this problematic specifically for pins or any root package in general?

IIRC if a root package has a test dependency it will currently be still fetched.

**Comment by NathanReb** [comment]
It's problematic for pins only, I think you pretty much always want the test dependencies of your root packages. What's problematic here is that it seems to pull in test dependencies of the pinned package in addition.
