### ISSUE TITLE
add a version field to cloned vendored projects

### ISSUE THREAD

**Issue by avsm** [ocamllabs/opam-monorepo#90]
This needs to go in `dune-project` to correctly set the version for the build-info of that vendored project.

**Comment by samoht** [comment]
and ideally duniverse should replay everything that `dune-release` is doing on release. Maybe there's a way to either call `dune-release` and/or to use it as a library. /cc @NathanReb and @gpetiot to have their feedback.

**Comment by avsm** [comment]
This would be very useful (everything short of releasing it onto opam-repository, of course ;-)
